{
    'name': 'Teidesat Website',
    'version': '1.0',
    'summary': 'Custom website for Teidesat',
    'category': 'Website',
    'depends': ['website'],
    'data': [
        'views/pages/home.xml',
        'views/pages/divulgacion.xml',
        'views/pages/nosotros.xml',
        'views/pages/departamentos.xml',
        'views/pages/participa.xml',
        'views/pages/contacto.xml',
        'views/pages/it_departamento.xml',
        'views/pages/arte_departamento.xml',
        'views/pages/divulgacion_departamento.xml',
        'views/pages/ads_departamento.xml',
        'views/pages/mecanica_departamento.xml',
        'views/pages/administracion_departamento.xml',
        'views/pages/rd_departamento.xml',
        'views/pages/electrocom_departamento.xml',
        'views/pages/404.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'teidesat_website/static/src/css/home.css',
            'teidesat_website/static/src/css/divulgacion.css',
            'teidesat_website/static/src/css/nosotros.css',
            'teidesat_website/static/src/js/home.js',
            'teidesat_website/static/src/css/departamentos.css',
            'teidesat_website/static/src/css/participa.css',
            'teidesat_website/static/src/css/contacto.css',
            'teidesat_website/static/src/js/departamentos.js',
            'teidesat_website/static/src/css/departamento_detalle.css',
            'teidesat_website/static/src/css/404.css',
            'teidesat_website/static/src/js/404.js',
            'teidesat_website/static/src/js/contacto.js',
        ],
    },
    'installable': True,
    'application': True,
}